Hero heading
practicum-webdev-2/responsive-page pull request #10
Opened 2023-09-18 12:18 UTC by vinib96

Adicionamos classes html e estilos css para o bloco "hero" versão desktop 
![image](https://github.com/tripleten-wd-brazil/responsive-page/assets/141737376/e89088db-30fd-49d9-928c-c43a1191be58)

2023-10-04 12:38 UTC, thiagopuntar requested changes
Fala pessoal, tudo certo? 
A responsividade nao está funcionando muito bem em telas grandes
![image](https://github.com/tripleten-wd-brazil/responsive-page/assets/35710202/b2805b92-42f2-43e4-9553-9c104f8b812f)

E em telas muito pequenas também está um pouco esquisito (a imagem está cortando embaixo), tentem mexer na questão do background size de repente. Essa imagem de fato é bem ruim, mas de repente dá pra gente trabalhar alguma coisa.

![image](https://github.com/tripleten-wd-brazil/responsive-page/assets/35710202/12d02d82-929c-40d5-9452-11b1c58223f2)

Outro ponto, a fonte já está importada na cohort8/main, nao precisa importar novamente em ttf. Podem remover elas.

2023-10-04 12:38 UTC, thiagopuntar commented on blocks/hero.css
> +  margin: 117px 653px 148px 122px;
Lembrem de evitar utilizar essas margins grandes nas laterais. O ideal é usar o margin-inline: auto.

2023-10-04 12:38 UTC, thiagopuntar commented on blocks/hero.css
> +  line-height: 36px;
line-height sempre em proporção

2023-10-05 12:23 UTC, Bianchi-marina commented
Atualizei o código :) Aguardamos revisão.

2023-10-05 22:26 UTC, thiagopuntar approved these changes
Pessoal, só coloquei umas recomendações em geral para evitar utilizar essas unidades de padding e margin em %, muito por conta que a % é em relação a width do elemento (mesmo que seja padding e margin pra top ou bottom).
Então pode causar alguns comportamentos estranhos ou não esperados.
Mas isso não é um blocker, estou aprovando a PR e vamos mergear, blz?

Meus parabéns, foi um excelente trabalho.

2023-10-05 22:26 UTC, thiagopuntar commented on blocks/hero.css
> +  margin-left: 10%;
Aqui está funcionando bacana, mas cuidado com margin em %, porque muitas vezes dá mais dor de cabeça do que resolve problemas, foquem sempre que possível na margin lateral auto.

2023-10-05 22:26 UTC, thiagopuntar commented on blocks/hero.css
> +  padding-left: 3%;
Esses paddings em % muitas vezes não ajudam muito também.. mais vale as vezes usar um valor fixo em px para estar unidade.

2023-10-05 22:26 UTC, merged